(test
 (name naive)
 (modules naive correctness)
 (libraries mrtccsl alcotest))

(test
 (name symbolic)
 (modules symbolic correctness)
 (libraries mrtccsl alcotest))

(test
 (name diagram)
 (modules diagram correctness)
 (libraries mrtccsl alcotest))

(test
 (name induction)
 (modules induction)
 (libraries mrtccsl alcotest))

(test
 (name parser)
 (libraries mrtccsl.mrtccslparsing mrtccsl)
 (deps
  (glob_files code/*.mrtccsl)))

(executable
 (public_name bisimulation)
 (name bisimulation)
 (modules bisimulation)
 (libraries mrtccsl mrtccsl.mrtccslparsing))

(executable
 (public_name bdd_complexity)
 (name bdd_complexity)
 (modules bdd_complexity)
 (libraries mrtccsl mtime.clock))

(env
 (dev
  (flags
   (:standard -warn-error -A))))
